/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gralde_FirstAidApp;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testAppHasAGreeting() {
        gralde_FirstAidApp.Main classUnderTest = new gralde_FirstAidApp.Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
