/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstAidApp;

import FirstAidApp.GUI.Menu;
import FirstAidApp.templates.Lesson;
import FirstAidApp.templates.Quiz;
import FirstAidApp.templates.Settings;
import FirstAidApp.templates.relations.DescriptionImage;

import javax.swing.*;
import java.util.ArrayList;

/* TODO: I need to somehow link all the different forms together. This is so one form can switch to another.
    (For now I'm just going to have each panel from the menu generate it's own form.) */

public class Main {

    public static void main(String[] args) {
        System.out.println("Running program...");
        testData();
    }

    public static void testData() {
        ArrayList<DescriptionImage> content = new ArrayList();
        content.add(new DescriptionImage("This is a test", "./root", "Just a test image"));
        Lesson lesson = new Lesson("Title", content);
        System.out.println(String.format("Lesson   -> title              -> %s", lesson.getTitle()));
        System.out.println(String.format("         -> description        -> %s", lesson.getDescription(0)));
        System.out.println(String.format("         -> image              -> %s", lesson.getImage(0)));
        System.out.println(String.format("         -> image caption      -> %s", lesson.getImageCaption(0)));

        Settings settings = new Settings(false, false, Settings.colorBlind.DEUTERANOPIA);
        System.out.println(String.format("Settings -> magnifyText        -> %s", settings.getMagnifyText()));
        System.out.println(String.format("         -> captionImage       -> %s", settings.getCaptionImages()));
        System.out.println(String.format("         -> Color blind option -> %s", settings.getColorBlind()));

        Quiz quiz = new Quiz("Title", "Question", "CorrectAnswer", "FakeAnswer1", "FakeAnswer2", "FakeAnswer3");
        System.out.println(String.format("Quiz     -> Title              -> %s", quiz.getTitle()));
        System.out.println(String.format("         -> Fake Answer 3      -> %s", quiz.getFakeAnswer(0)));
        System.out.println(String.format("         -> Correct Answer     -> %s", quiz.getCorrectAnswer()));

        try {
            ArrayList<String> fakeAnswers = new ArrayList();
            fakeAnswers.add("test");
            Quiz badQuiz = new Quiz("title", "Question", "CorrectAnswer", fakeAnswers);
        } catch(Error e) {
            System.out.println(e.getMessage());
        }
    }

    public static void createGUI() {
        JFrame frame = new JFrame();
        frame = new JFrame("Menu");
        frame.setContentPane(new Menu().viewMenu);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
